import type { ScenarioFamilyName } from "./families.js";

const SIMULATION_SIGNALS: Record<string, number> = {
  orchestrat: 2.0,
  rollback: 2.0,
  deploy: 1.5,
  pipeline: 1.5,
  workflow: 1.5,
  incident: 1.5,
  remediat: 1.5,
  triage: 1.5,
  "state machine": 2.0,
  "mock api": 2.0,
  "mock environment": 2.0,
  "api call": 1.5,
  endpoint: 1.0,
  microservice: 1.5,
  "service health": 1.5,
  monitor: 1.0,
  dashboard: 1.0,
  recovery: 1.5,
  failover: 2.0,
  "circuit breaker": 2.0,
  retry: 1.0,
  "dependency order": 2.0,
  "correct order": 1.5,
  "action trace": 2.0,
  "side effect": 1.5,
  transact: 1.5,
  simulat: 1.0,
  trace: 1.0,
  "step by step": 1.0,
  "health endpoint": 1.5,
  "server log": 1.0,
  "root cause": 1.0,
  investigat: 1.0,
};

const AGENT_TASK_SIGNALS: Record<string, number> = {
  essay: 2.0,
  article: 1.5,
  blog: 1.5,
  "blog post": 2.0,
  "write about": 1.5,
  persuasive: 1.5,
  narrative: 1.0,
  poem: 1.5,
  haiku: 1.5,
  story: 1.0,
  fiction: 1.5,
  prose: 1.5,
  recipe: 1.5,
  summariz: 1.5,
  abstract: 1.0,
  generat: 1.0,
  translat: 1.5,
  classify: 1.0,
  sentiment: 1.5,
  report: 1.0,
  review: 1.0,
  evaluat: 1.0,
  "code quality": 1.5,
  "python function": 1.5,
  sort: 0.5,
  "data analysis": 1.0,
  "customer review": 1.0,
};

const GAME_SIGNALS: Record<string, number> = {
  tournament: 2.0,
  "board game": 2.0,
  compet: 1.5,
  "two-player": 2.0,
  "two player": 2.0,
  "head-to-head": 2.0,
  "head to head": 2.0,
  opponent: 1.5,
  territory: 1.5,
  "capture the flag": 2.0,
  "grid game": 2.0,
  maze: 1.0,
  "strategy game": 2.0,
  "resource management": 1.5,
  scoring: 1.0,
  elo: 2.0,
  ranking: 1.0,
  win: 0.5,
  lose: 0.5,
  match: 0.5,
  player: 1.0,
};

const ARTIFACT_EDITING_SIGNALS: Record<string, number> = {
  "edit file": 2.0,
  "modify file": 2.0,
  "update config": 2.0,
  configuration: 1.5,
  "config file": 1.5,
  yaml: 1.5,
  json: 1.0,
  schema: 1.5,
  migration: 1.5,
  manifest: 1.5,
  patch: 1.0,
  "refactor config": 2.0,
  "fix config": 2.0,
  artifact: 1.5,
  "file edit": 2.0,
  rewrite: 1.0,
  "update policy": 1.5,
  "change file": 1.5,
  "modify yaml": 2.0,
  "modify json": 2.0,
  "config repair": 2.0,
  "repair schema": 2.0,
  "sql migration": 2.0,
  dockerfile: 1.5,
};

const INVESTIGATION_SIGNALS: Record<string, number> = {
  investigat: 2.0,
  evidence: 2.0,
  "red herring": 2.0,
  clue: 1.5,
  forensic: 1.5,
  "root cause": 1.5,
  diagnos: 2.0,
  hypothesis: 1.5,
  "log analysis": 1.5,
  "incident timeline": 1.5,
  "query logs": 1.5,
  triangulate: 1.5,
};

const WORKFLOW_SIGNALS: Record<string, number> = {
  transaction: 2.0,
  "workflow step": 2.0,
  compensation: 2.0,
  rollback: 1.5,
  retry: 1.5,
  "side effect": 2.0,
  "order processing": 2.0,
  payment: 1.5,
  idempotent: 1.5,
  reversible: 1.5,
  fulfillment: 1.5,
  "approval workflow": 2.0,
  "multi-step transaction": 2.0,
};

const SCHEMA_EVOLUTION_SIGNALS: Record<string, number> = {
  "schema evolv": 2.0,
  "schema evolution": 2.0,
  "stale context": 2.0,
  "schema migration": 2.0,
  "breaking change": 2.0,
  "schema version": 2.0,
  "field removed": 1.5,
  "field added": 1.5,
  "field renamed": 1.5,
  "context invalidat": 2.0,
  "stale assumption": 2.0,
  "data model change": 1.5,
  "schema drift": 1.5,
  "backwards compat": 1.5,
};

const TOOL_FRAGILITY_SIGNALS: Record<string, number> = {
  "tool drift": 2.0,
  "api contract": 2.0,
  "tool fragility": 2.0,
  "environment drift": 2.0,
  "broken tool": 2.0,
  "tool version": 1.5,
  "api change": 1.5,
  "response format change": 2.0,
  "tool adapt": 1.5,
  "tool break": 1.5,
  "contract drift": 2.0,
  "endpoint deprecat": 1.5,
  "api deprecat": 1.5,
  "tool failure": 1.5,
};

const NEGOTIATION_SIGNALS: Record<string, number> = {
  negotiat: 2.0,
  adversarial: 1.5,
  batna: 2.0,
  "hidden preference": 2.0,
  "reservation value": 1.5,
  "aspiration value": 1.5,
  counteroffer: 1.5,
  "counter offer": 1.5,
  "deal quality": 1.5,
  "opponent modeling": 2.0,
  anchoring: 1.0,
  seller: 1.0,
  buyer: 1.0,
  concession: 1.0,
};

const OPERATOR_LOOP_SIGNALS: Record<string, number> = {
  escalat: 2.0,
  operator: 1.5,
  clarification: 1.5,
  "human in the loop": 2.0,
  "human-in-the-loop": 2.0,
  "over-escalat": 2.0,
  "under-escalat": 2.0,
  triage: 1.0,
  "when to escalate": 2.0,
  "operator loop": 2.0,
};

const COORDINATION_SIGNALS: Record<string, number> = {
  coordinat: 2.0,
  handoff: 2.0,
  "multi-agent": 2.0,
  "multi agent": 2.0,
  worker: 1.5,
  merge: 1.5,
  duplication: 1.5,
  parallel: 1.0,
  teammate: 1.0,
  collaborator: 1.0,
  "role split": 1.5,
  "partial context": 2.0,
};

export const FAMILY_SIGNAL_GROUPS: Record<ScenarioFamilyName, Record<string, number>> = {
  game: GAME_SIGNALS,
  agent_task: AGENT_TASK_SIGNALS,
  simulation: SIMULATION_SIGNALS,
  artifact_editing: ARTIFACT_EDITING_SIGNALS,
  investigation: INVESTIGATION_SIGNALS,
  workflow: WORKFLOW_SIGNALS,
  schema_evolution: SCHEMA_EVOLUTION_SIGNALS,
  tool_fragility: TOOL_FRAGILITY_SIGNALS,
  negotiation: NEGOTIATION_SIGNALS,
  operator_loop: OPERATOR_LOOP_SIGNALS,
  coordination: COORDINATION_SIGNALS,
};

export const DEFAULT_FAMILY_NAME: ScenarioFamilyName = "agent_task";
