from __future__ import annotations

import json
import logging
import math
import re
from dataclasses import dataclass, field
from typing import Literal

from autocontext.agents.types import LlmFn
from autocontext.execution.rubric_coherence import check_rubric_coherence
from autocontext.providers.base import LLMProvider
from autocontext.providers.callable_wrapper import CallableProvider

logger = logging.getLogger(__name__)


ParseMethod = Literal["raw_json", "code_block", "markers", "plaintext", "none"]


@dataclass(slots=True)
class DisagreementMetrics:
    """Evaluator disagreement statistics from multi-sample judge evaluation."""

    score_std_dev: float = 0.0
    score_range: tuple[float, float] = (0.0, 0.0)
    sample_scores: list[float] = field(default_factory=list)
    dimension_std_devs: dict[str, float] = field(default_factory=dict)
    is_high_disagreement: bool = False
    sample_count: int = 1

    def to_dict(self) -> dict[str, object]:
        return {
            "score_std_dev": self.score_std_dev,
            "score_range": list(self.score_range),
            "sample_scores": self.sample_scores,
            "dimension_std_devs": self.dimension_std_devs,
            "is_high_disagreement": self.is_high_disagreement,
            "sample_count": self.sample_count,
        }


@dataclass(slots=True)
class JudgeResult:
    """Result from LLM judge evaluation."""

    score: float
    reasoning: str
    dimension_scores: dict[str, float] = field(default_factory=dict)
    raw_responses: list[str] = field(default_factory=list)
    parse_method: ParseMethod = "none"
    internal_retries: int = 0
    dimensions_were_generated: bool = False
    disagreement: DisagreementMetrics | None = None


_RESULT_START = "<!-- JUDGE_RESULT_START -->"
_RESULT_END = "<!-- JUDGE_RESULT_END -->"

DEFAULT_FACTUAL_CONFIDENCE = 0.5


def _detect_generated_dimensions(dimension_keys: list[str], rubric: str) -> bool:
    """Detect whether dimension keys were generated by the judge rather than
    derived from the rubric.

    Uses a simple heuristic: split each key on ``_`` and check whether any
    fragment appears as a word in the rubric text (case-insensitive).
    """
    if not dimension_keys:
        return False
    rubric_lower = rubric.lower()
    rubric_words = set(re.split(r"\W+", rubric_lower))
    rubric_words.discard("")

    for key in dimension_keys:
        key_lower = key.lower()
        # Exact match — the key itself appears in the rubric as-is
        if key_lower in rubric_words:
            continue
        # Fragment match — any underscore-delimited part appears
        fragments = [f for f in key_lower.split("_") if f]
        if not any(frag in rubric_words for frag in fragments):
            return True
    return False


class LLMJudge:
    """LLM-based judge for evaluating agent task outputs.

    Accepts either a ``provider: LLMProvider`` or a legacy
    ``llm_fn: LlmFn`` for backward compatibility.
    """

    def __init__(
        self,
        model: str,
        rubric: str,
        llm_fn: LlmFn | None = None,
        provider: LLMProvider | None = None,
        samples: int = 1,
        temperature: float = 0.0,
        check_coherence: bool = False,
        disagreement_threshold: float = 0.15,
    ) -> None:
        if provider is not None:
            self.provider = provider
        elif llm_fn is not None:
            self.provider = CallableProvider(llm_fn, model_name=model)
        else:
            raise ValueError("Either 'provider' or 'llm_fn' must be provided")

        self.model = model
        self.rubric = rubric
        self.samples = max(1, samples)
        self.temperature = temperature

        # Backward-compatible property
        self.llm_fn = llm_fn

        # Disagreement threshold for flagging high evaluator disagreement
        self._disagreement_threshold = disagreement_threshold

        # Optional rubric coherence pre-check
        self._rubric_warnings: list[str] = []
        if check_coherence:
            coherence = check_rubric_coherence(rubric)
            self._rubric_warnings = coherence.warnings

    @property
    def rubric_warnings(self) -> list[str]:
        """Warnings from rubric coherence pre-check (empty if not enabled)."""
        return self._rubric_warnings

    def evaluate(
        self,
        task_prompt: str,
        agent_output: str,
        reference_context: str | None = None,
        required_concepts: list[str] | None = None,
        calibration_examples: list[dict] | None = None,
        pinned_dimensions: list[str] | None = None,
    ) -> JudgeResult:
        """Evaluate agent output by calling the provider N times and averaging."""
        system_prompt = (
            "You are an expert judge evaluating an AI agent's output. "
            "Evaluate the output against the provided rubric. "
        )
        if reference_context:
            system_prompt += (
                "You have been provided with authoritative reference context. "
                "You MUST evaluate factual accuracy against this reference. "
                "Any claims that contradict the reference context should be penalized heavily. "
                "Include a 'factual_accuracy' dimension in your scoring. "
                "Also include a 'factual_confidence' dimension (0.0-1.0) expressing how confident "
                "you are in your factual accuracy assessment — 1.0 means all claims are easily "
                "verifiable against the reference, 0.0 means claims are beyond your ability to verify. "
            )
        system_prompt += (
            "Output your evaluation between <!-- JUDGE_RESULT_START --> and <!-- JUDGE_RESULT_END --> markers "
            'containing JSON: {"score": 0.0-1.0, "reasoning": "...", "dimensions": {"dim1": 0.0-1.0, ...}}'
        )
        user_prompt = self._build_judge_prompt(
            task_prompt, agent_output, reference_context, required_concepts, calibration_examples,
            pinned_dimensions,
        )

        scores: list[float] = []
        reasonings: list[str] = []
        all_dims: list[dict[str, float]] = []
        raw_responses: list[str] = []
        total_internal_retries = 0
        last_parse_method: ParseMethod = "none"

        for _ in range(self.samples):
            dims: dict[str, float] = {}
            score, reasoning = 0.0, ""
            sample_parse_method: ParseMethod = "none"
            # Retry up to 2 times on parse failure
            for attempt in range(2):
                result = self.provider.complete(
                    system_prompt=system_prompt,
                    user_prompt=user_prompt,
                    model=self.model,
                    temperature=self.temperature,
                )
                response = result.text
                raw_responses.append(response)
                score, reasoning, dims, sample_parse_method = self._parse_judge_response(response)
                if score > 0.0 or "Failed to parse" not in reasoning:
                    break
                total_internal_retries += 1
                logger.warning("judge parse failed (attempt %d), retrying", attempt + 1)
            scores.append(score)
            reasonings.append(reasoning)
            all_dims.append(dims)
            last_parse_method = sample_parse_method

        avg_score = sum(scores) / len(scores)

        # Average dimension scores
        avg_dims: dict[str, float] = {}
        all_keys: set[str] = set()
        if all_dims:
            for d in all_dims:
                all_keys.update(d.keys())
            for key in all_keys:
                vals = [d[key] for d in all_dims if key in d]
                avg_dims[key] = sum(vals) / len(vals) if vals else 0.0

        # Compute disagreement metrics when multiple samples
        disagreement: DisagreementMetrics | None = None
        if len(scores) > 1:
            mean = avg_score
            variance = sum((s - mean) ** 2 for s in scores) / len(scores)
            std_dev = math.sqrt(variance)

            dim_std_devs: dict[str, float] = {}
            for key in all_keys:
                dim_vals = [d[key] for d in all_dims if key in d]
                if len(dim_vals) > 1:
                    dim_mean = sum(dim_vals) / len(dim_vals)
                    dim_var = sum((v - dim_mean) ** 2 for v in dim_vals) / len(dim_vals)
                    dim_std_devs[key] = math.sqrt(dim_var)

            disagreement = DisagreementMetrics(
                score_std_dev=std_dev,
                score_range=(min(scores), max(scores)),
                sample_scores=list(scores),
                dimension_std_devs=dim_std_devs,
                is_high_disagreement=std_dev > self._disagreement_threshold,
                sample_count=len(scores),
            )

        # Ensure factual dimensions exist when reference context provided.
        # Skip when pinned_dimensions is set — respect the explicit constraint.
        if reference_context and not pinned_dimensions:
            if "factual_accuracy" not in avg_dims:
                avg_dims["factual_accuracy"] = avg_score
            if "factual_confidence" not in avg_dims:
                # Default confidence: moderate when reference context available.
                # The judge cannot verify claims against external sources beyond
                # its training data — this is self-reported confidence only.
                avg_dims["factual_confidence"] = DEFAULT_FACTUAL_CONFIDENCE

        combined_reasoning = "\n---\n".join(reasonings)

        dimensions_were_generated = _detect_generated_dimensions(
            list(avg_dims.keys()), self.rubric,
        )

        return JudgeResult(
            score=avg_score,
            reasoning=combined_reasoning,
            dimension_scores=avg_dims,
            raw_responses=raw_responses,
            parse_method=last_parse_method,
            internal_retries=total_internal_retries,
            dimensions_were_generated=dimensions_were_generated,
            disagreement=disagreement,
        )

    def _build_judge_prompt(
        self,
        task_prompt: str,
        agent_output: str,
        reference_context: str | None = None,
        required_concepts: list[str] | None = None,
        calibration_examples: list[dict] | None = None,
        pinned_dimensions: list[str] | None = None,
    ) -> str:
        parts = [
            f"## Rubric\n{self.rubric}\n",
        ]
        if reference_context:
            parts.append(
                f"\n## Reference Context (Authoritative)\n{reference_context}\n"
            )
        if required_concepts:
            concepts_list = ", ".join(required_concepts)
            parts.append(
                f"\n## Required Concepts\nThe output MUST correctly address these concepts: {concepts_list}\n"
            )
        if calibration_examples:
            cal_lines = ["\n## Calibration Examples (Human-Scored)\n"]
            cal_lines.append(
                "The following are real outputs scored by a human reviewer. "
                "Use these to calibrate your scoring — match the human's standards.\n"
            )
            for i, ex in enumerate(calibration_examples, 1):
                score = ex.get("human_score", "N/A")
                notes = ex.get("human_notes", "")
                output_snippet = ex.get("agent_output", "")[:200]
                cal_lines.append(
                    f"**Example {i}** — Score: {score}\n"
                    f"Human notes: {notes}\n"
                    f"Output snippet: {output_snippet}...\n"
                )
            parts.append("\n".join(cal_lines))
        if pinned_dimensions:
            dim_list = ", ".join(pinned_dimensions)
            parts.append(
                f"\n## Required Dimensions\n"
                f"You MUST use exactly these dimension names in your scoring: {dim_list}\n"
                f"Do not add, remove, or rename dimensions. Score each one between 0.0 and 1.0.\n"
            )
        parts.append(f"\n## Task Prompt\n{task_prompt}\n")
        parts.append(f"\n## Agent Output\n{agent_output}\n")
        parts.append(
            "\nEvaluate the agent's output against the rubric. "
            "Provide your evaluation between <!-- JUDGE_RESULT_START --> and <!-- JUDGE_RESULT_END --> markers.\n\n"
            "You MUST use exactly this format:\n"
            "<!-- JUDGE_RESULT_START -->\n"
            '{"score": 0.85, "reasoning": "Your detailed reasoning here", '
            '"dimensions": {"dimension_name": 0.9, "other_dimension": 0.8}}\n'
            "<!-- JUDGE_RESULT_END -->\n\n"
            "The score and all dimension values must be between 0.0 and 1.0. "
            "Include dimension scores that match the rubric criteria."
        )
        return "\n".join(parts)

    def _parse_judge_response(self, response: str) -> tuple[float, str, dict[str, float], ParseMethod]:
        """Parse judge response using multiple strategies.

        Strategies (tried in order):
        1. Marker-based: extract JSON between <!-- JUDGE_RESULT_START/END -->
        2. Raw JSON: find a JSON object with "score" key anywhere in response
        3. Code block: extract JSON from ```json ... ``` blocks
        4. Plain text: regex for "score": X.XX or "Score: X.XX" patterns
        """
        # Strategy 1: Marker-based (preferred — matches our system prompt format)
        data = self._try_marker_parse(response)
        if data is not None:
            return self._extract_from_dict(data, "markers")

        # Strategy 2: Raw JSON object with "score" key
        data = self._try_raw_json_parse(response)
        if data is not None:
            return self._extract_from_dict(data, "raw_json")

        # Strategy 3: JSON code block
        data = self._try_code_block_parse(response)
        if data is not None:
            return self._extract_from_dict(data, "code_block")

        # Strategy 4: Plain text score extraction
        result = self._try_plaintext_parse(response)
        if result is not None:
            return (*result, "plaintext")

        return 0.0, "Failed to parse judge response: no parseable score found", {}, "none"

    @staticmethod
    def _try_marker_parse(response: str) -> dict | None:
        """Strategy 1: Extract JSON between JUDGE_RESULT markers."""
        pattern = re.compile(
            re.escape(_RESULT_START) + r"\s*(.*?)\s*" + re.escape(_RESULT_END),
            re.DOTALL,
        )
        match = pattern.search(response)
        if not match:
            return None
        try:
            data: dict = json.loads(match.group(1))
            return data
        except (json.JSONDecodeError, TypeError):
            return None

    @staticmethod
    def _try_code_block_parse(response: str) -> dict | None:
        """Strategy 2: Extract JSON from ```json ... ``` code blocks."""
        pattern = re.compile(r"```(?:json)?\s*\n?(.*?)\n?```", re.DOTALL)
        for match in pattern.finditer(response):
            try:
                data = json.loads(match.group(1).strip())
                if isinstance(data, dict) and "score" in data:
                    return data
            except (json.JSONDecodeError, TypeError):
                continue
        return None

    @staticmethod
    def _try_raw_json_parse(response: str) -> dict | None:
        """Strategy 3: Find a JSON object containing 'score' key."""
        # Look for JSON objects in the response
        for match in re.finditer(r'\{[^{}]*"score"[^{}]*\}', response):
            try:
                data = json.loads(match.group(0))
                if isinstance(data, dict) and "score" in data:
                    return data
            except (json.JSONDecodeError, TypeError):
                continue
        # Try nested objects (with dimensions)
        for match in re.finditer(r'\{(?:[^{}]|\{[^{}]*\})*"score"(?:[^{}]|\{[^{}]*\})*\}', response):
            try:
                data = json.loads(match.group(0))
                if isinstance(data, dict) and "score" in data:
                    return data
            except (json.JSONDecodeError, TypeError):
                continue
        return None

    @staticmethod
    def _try_plaintext_parse(response: str) -> tuple[float, str, dict[str, float]] | None:
        """Strategy 4: Extract score from plain text patterns."""
        # Match patterns like "Score: 0.85" or "Overall score: 0.9"
        patterns = [
            r'(?:overall\s+)?score[:\s]+([01](?:\.\d+)?)',
            r'"score"\s*:\s*([01](?:\.\d+)?)',
            r'(\d\.\d+)\s*/\s*1\.0',
        ]
        for pat in patterns:
            match = re.search(pat, response, re.IGNORECASE)
            if match:
                try:
                    score = float(match.group(1))
                    if 0.0 <= score <= 1.0:
                        # Use the full response as reasoning since we couldn't parse structured
                        reasoning = response[:500] if len(response) > 500 else response
                        return score, reasoning, {}
                except (ValueError, IndexError):
                    continue
        return None

    @staticmethod
    def _extract_from_dict(
        data: dict, method: ParseMethod,
    ) -> tuple[float, str, dict[str, float], ParseMethod]:
        """Extract score, reasoning, dimensions, and parse method from a parsed dict."""
        score = float(data.get("score", 0.0))
        score = max(0.0, min(1.0, score))
        reasoning = str(data.get("reasoning", ""))
        dimensions = data.get("dimensions", {})
        dim_scores: dict[str, float] = {}
        for k, v in dimensions.items():
            try:
                dim_scores[str(k)] = max(0.0, min(1.0, float(v)))
            except (ValueError, TypeError):
                continue
        return score, reasoning, dim_scores, method
