// PR body renderer (§9.4).
//
// Deterministic: the output is a pure function of the inputs. No Date.now(),
// no random identifiers — the caller threads a timestamp and an autocontext
// version through so CI can hash the output and detect "nothing changed since
// last run."
//
// Section headers are stable + machine-parseable per the spec: downstream
// consumers (PR-comment bots, audit scrapers) can reliably locate each block
// without parsing prose.

import type { Artifact, EvalRun, PromotionDecision, RollbackStrategy } from "../contract/types.js";

export interface RenderPrBodyInputs {
  readonly candidate: Artifact;
  readonly baseline: Artifact | null;
  readonly decision: PromotionDecision;
  readonly evalRun: EvalRun;
  /** autocontext package version; appears in Audit footer. */
  readonly autocontextVersion: string;
  /** ISO-8601 timestamp captured upstream; appears in Audit footer. */
  readonly timestamp: string;
}

/**
 * Render a markdown PR body per spec §9.4. Pure function.
 */
export function renderPrBody(inputs: RenderPrBodyInputs): string {
  const { candidate, baseline, decision, evalRun, autocontextVersion, timestamp } = inputs;

  const qualityLabel = qualityBand(decision);
  const recommended = decision.recommendedTargetState;
  const confidenceStr = decision.confidence.toFixed(2);

  const baselineRef = baseline === null ? "no incumbent" : baseline.id;
  const signed = signatureNote(candidate);

  const lines: string[] = [];

  // ---- Header ----
  lines.push(
    `## Autocontext candidate promotion: ${candidate.actuatorType} for ${candidate.scenario}`,
  );
  lines.push("");
  lines.push(
    `Candidate \`${candidate.id}\` → replacing baseline \`${baselineRef}\``,
  );
  lines.push(
    `Environment: \`${candidate.environmentTag}\` · Eval suite: \`${evalRun.suiteId}\``,
  );
  lines.push(
    `Decision: **${qualityLabel}** → recommended state \`${recommended}\` · confidence \`${confidenceStr}\``,
  );
  lines.push("");

  // ---- Metric deltas ----
  lines.push("### Metric deltas");
  lines.push("| Dimension | Baseline | Candidate | Δ | Passed |");
  lines.push("| --- | --- | --- | --- | --- |");
  const q = decision.deltas.quality;
  lines.push(
    `| Quality | ${num(q.baseline)} | ${num(q.candidate)} | ${signed3(q.delta)} | ${checkmark(q.passed)} |`,
  );
  const c = decision.deltas.cost;
  lines.push(
    `| Cost (tokensOut) | ${c.baseline.tokensOut} | ${c.candidate.tokensOut} | ${signedInt(c.delta.tokensOut)} | ${checkmark(c.passed)} |`,
  );
  const l = decision.deltas.latency;
  lines.push(
    `| Latency (p95ms) | ${l.baseline.p95Ms} | ${l.candidate.p95Ms} | ${signedInt(l.delta.p95Ms)} | ${checkmark(l.passed)} |`,
  );
  const s = decision.deltas.safety;
  const regCount = s.regressions.length;
  lines.push(
    `| Safety regressions | — | ${regCount} | — | ${checkmark(s.passed)} |`,
  );
  lines.push("");

  // ---- Dataset provenance ----
  lines.push("### Dataset provenance");
  lines.push(`- Dataset: \`${evalRun.datasetProvenance.datasetId}\``);
  lines.push(`- Slice hash: \`${evalRun.datasetProvenance.sliceHash}\``);
  lines.push(`- Sample count: ${evalRun.datasetProvenance.sampleCount}`);
  lines.push(
    `- Eval runner: \`${evalRun.metrics.evalRunnerIdentity.name} ${evalRun.metrics.evalRunnerIdentity.version}\` (configHash \`${evalRun.metrics.evalRunnerIdentity.configHash}\`)`,
  );
  lines.push("");

  // ---- Rollback ----
  lines.push("### Rollback");
  const rollback = rollbackForActuator(candidate.actuatorType);
  lines.push(
    `Strategy: \`${rollback.kind}\` (${candidate.actuatorType}).`,
  );
  lines.push(
    `To undo: \`autoctx candidate rollback ${candidate.id} --reason "..."\` — ${describeRollback(rollback, candidate.actuatorType)}.`,
  );
  lines.push("");

  // ---- Lineage ----
  lines.push("### Lineage");
  const parents = candidate.provenance.parentArtifactIds;
  if (parents.length === 0) {
    lines.push("Parent artifacts: _(none — root candidate)_");
  } else {
    lines.push(
      `Parent artifacts: ${parents.map((p) => `\`${p}\``).join(", ")}`,
    );
  }
  lines.push("");

  // ---- Audit ----
  lines.push("### Audit");
  lines.push(`- Artifact payload hash: \`${candidate.payloadHash}\``);
  lines.push(
    `- Signed: ${signed} · Schema version: ${candidate.schemaVersion}`,
  );
  lines.push(
    `- Generated by: autocontext v${autocontextVersion} at ${timestamp}`,
  );
  lines.push("- Full decision JSON: attached as `decision.json`");
  lines.push("");

  // Trailing newline keeps the file POSIX-compliant and diff-friendly.
  return lines.join("\n");
}

// ---- Helpers ----

function qualityBand(d: PromotionDecision): string {
  if (!d.pass) return "HARD FAIL";
  switch (d.recommendedTargetState) {
    case "active":
      return "STRONG";
    case "canary":
      return "MODERATE";
    case "shadow":
      return "MARGINAL";
    case "disabled":
      return "HARD FAIL";
  }
}

function num(n: number): string {
  return Number.isInteger(n) ? String(n) : n.toFixed(3);
}

function signed3(n: number): string {
  const s = n >= 0 ? "+" : "";
  return `${s}${n.toFixed(3)}`;
}

function signedInt(n: number): string {
  const s = n > 0 ? "+" : "";
  return `${s}${n}`;
}

function checkmark(passed: boolean): string {
  return passed ? "✓" : "✗";
}

function signatureNote(candidate: Artifact): string {
  const lastEvent = candidate.promotionHistory[candidate.promotionHistory.length - 1];
  return lastEvent?.signature ? "yes" : "no";
}

function rollbackForActuator(
  t: Artifact["actuatorType"],
): RollbackStrategy {
  switch (t) {
    case "prompt-patch":
      return { kind: "content-revert" };
    case "tool-policy":
      return { kind: "content-revert" };
    case "routing-rule":
      return { kind: "cascade-set", dependsOn: ["tool-policy"] };
    case "fine-tuned-model":
      return { kind: "pointer-flip" };
    case "model-routing":
      return { kind: "content-revert" };
  }
}

function describeRollback(strategy: RollbackStrategy, actuatorType: Artifact["actuatorType"]): string {
  switch (strategy.kind) {
    case "content-revert":
      return "re-writes the working-tree file to the previous baseline's contents";
    case "pointer-flip":
      return "flips the active-model pointer back to the prior baseline; no blob movement";
    case "cascade-set":
      return `refuses if any dependent (${strategy.dependsOn.join(", ")}) is in an incompatible state; operator must roll back dependents first`;
    default: {
      // Exhaustiveness guard: if a future RollbackStrategy kind is added, the
      // compiler will flag this case.
      const _exhaustive: never = strategy;
      void _exhaustive;
      return `(unknown rollback strategy for ${actuatorType})`;
    }
  }
}
