"""Tests for Gap 1: read_tool_context() returns full source, not truncated previews."""
from __future__ import annotations

from pathlib import Path

from autocontext.storage.artifacts import ArtifactStore


def _make_store(tmp_path: Path) -> ArtifactStore:
    return ArtifactStore(
        runs_root=tmp_path / "runs",
        knowledge_root=tmp_path / "knowledge",
        skills_root=tmp_path / "skills",
        claude_skills_path=tmp_path / ".claude" / "skills",
    )


def test_read_tool_context_returns_full_source(tmp_path: Path) -> None:
    store = _make_store(tmp_path)
    # Create a tool with more than 8 lines
    tool_code = "\n".join(f"line_{i} = {i}" for i in range(20))
    full_content = f'"""Generated by architect in generation 1.\n\nA test tool.\n"""\n\n{tool_code}\n'
    tool_dir = store.tools_dir("grid_ctf")
    tool_dir.mkdir(parents=True, exist_ok=True)
    (tool_dir / "long_tool.py").write_text(full_content, encoding="utf-8")

    context = store.read_tool_context("grid_ctf")
    # Must contain ALL 20 lines, not just the first 8
    for i in range(20):
        assert f"line_{i} = {i}" in context, f"Missing line_{i} — tool source was truncated"


def test_read_tool_context_separates_files(tmp_path: Path) -> None:
    store = _make_store(tmp_path)
    tool_dir = store.tools_dir("grid_ctf")
    tool_dir.mkdir(parents=True, exist_ok=True)
    (tool_dir / "alpha.py").write_text("def alpha(): pass\n", encoding="utf-8")
    (tool_dir / "beta.py").write_text("def beta(): pass\n", encoding="utf-8")

    context = store.read_tool_context("grid_ctf")
    assert "### alpha.py" in context
    assert "### beta.py" in context
    assert "def alpha(): pass" in context
    assert "def beta(): pass" in context


def test_read_tool_context_empty_dir(tmp_path: Path) -> None:
    store = _make_store(tmp_path)
    # No tools directory at all
    assert store.read_tool_context("grid_ctf") == "No generated tools available."

    # Empty directory
    store.tools_dir("grid_ctf").mkdir(parents=True, exist_ok=True)
    assert store.read_tool_context("grid_ctf") == "No generated tools available."


def test_read_tool_context_ignores_non_python(tmp_path: Path) -> None:
    store = _make_store(tmp_path)
    tool_dir = store.tools_dir("grid_ctf")
    tool_dir.mkdir(parents=True, exist_ok=True)
    (tool_dir / "valid.py").write_text("x = 1\n", encoding="utf-8")
    (tool_dir / "readme.md").write_text("# Not a tool\n", encoding="utf-8")
    (tool_dir / "data.json").write_text("{}\n", encoding="utf-8")

    context = store.read_tool_context("grid_ctf")
    assert "valid.py" in context
    assert "readme.md" not in context
    assert "data.json" not in context
